### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TekXS** [ender-null/polaris.py#6]
ninobot:~/workspace/polaris (master) $ ./runme.sh 
[nltk_data] Downloading package brown to /home/ubuntu/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /home/ubuntu/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/ubuntu/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /home/ubuntu/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to
[nltk_data]     /home/ubuntu/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.
Traceback (most recent call last):
  File "./loader.py", line 1, in <module>
    from polaris.types import AutosaveDict
ImportError: No module named polaris.types

**Comment by ender-null** [comment]
What version of python do you use?
