### ISSUE TITLE
Undefined load character map for types.py (crash)

### ISSUE THREAD

**Issue by ehs03y3ol** [ender-null/polaris.py#7]
> File "C:\Users\Ragezort\polaris-master\polaris\types.py", line 92, in load_database
>  json_data = file.read()
>   File "C:\Users\Ragezort\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2118: character maps to << undefined >>

suggestion to change line 91 to:

>     with open(self._database_file, "r", encoding='utf8') as file:

**Comment by ender-null** [comment]
Done, thank you ^^
